version: "1"
nodes:
  - id: apply-transforms
    name: Apply AST Transformations
    type: automatic
    steps:
      - name: Transform JSON named imports to default imports
        js-ast-grep:
          js_file: src/workflow.ts
          base_path: .
          include:
            - "**/*.tsx"
            - "**/*.ts"
            - "**/*.jsx"
            - "**/*.js"
            - "**/*.cts"
            - "**/*.mts"
          exclude:
            - "**/node_modules/**"
            - "**/dist/**"
            - "**/build/**"
            - "**/coverage/**"
            - "**/.next/**"
            - "**/out/**"
          language: typescript